packages:
  - 'packages/*'
  - 'packages/mobile/bookmarkaimobile'
  - 'packages/*/*/*'
  - 'python/*'

catalog:
  # Core dependencies
  axios: ^1.9.0
  uuid: ^11.1.0
  dotenv: ^16.5.0

  # Database
  pg: ^8.16.0
  ioredis: ^5.6.1

  # React ecosystem (using React 19 for React Native 0.79.2 compatibility)
  react: ^19.0.0
  react-dom: ^19.0.0
  react-test-renderer: ^19.0.0

  # Development tools
  typescript: ^5.8.3
  eslint: ^8.57.0
  prettier: ^3.2.5
  jest: ^29.7.0

  # TypeScript ESLint
  '@typescript-eslint/eslint-plugin': ^6.15.0
  '@typescript-eslint/parser': ^6.15.0

  # Types
  '@types/react': ^19.0.0
  '@types/react-dom': ^19.0.0
  '@types/jest': ^29.5.14
  '@types/node': ^20.0.0
  '@types/pg': ^8.15.1
  '@types/uuid': ^10.0.0

  # Common dev dependencies
  husky: ^8.0.3
  lint-staged: ^15.2.0
  chalk: ^4.1.2
  ts-prune: ^0.10.3
