groups:
  - name: ml_producer_alerts
    interval: 30s
    rules:
      # Connection Health Alerts
      - alert: MLProducerDisconnected
        expr: ml_producer_connection_state != 2
        for: 1m
        labels:
          severity: critical
          service: ml-producer
        annotations:
          summary: "ML Producer disconnected from RabbitMQ"
          description: "ML Producer has been disconnected from RabbitMQ for more than 1 minute. Current state: {{ $value }}"

      - alert: MLProducerHighReconnectAttempts
        expr: ml_producer_reconnect_attempts > 5
        for: 5m
        labels:
          severity: warning
          service: ml-producer
        annotations:
          summary: "ML Producer experiencing connection instability"
          description: "ML Producer has attempted {{ $value }} reconnections in the last 5 minutes"

      # Circuit Breaker Alerts
      - alert: MLProducerCircuitBreakerOpen
        expr: ml_producer_circuit_breaker_state == 1
        for: 30s
        labels:
          severity: critical
          service: ml-producer
        annotations:
          summary: "ML Producer circuit breaker is open"
          description: "ML Producer circuit breaker has been open for 30 seconds. No tasks are being processed."

      # Task Processing Alerts
      - alert: MLProducerHighFailureRate
        expr: |
          (
            rate(ml_producer_tasks_sent_total{status="failure"}[5m]) / 
            rate(ml_producer_tasks_sent_total[5m])
          ) > 0.1
        for: 5m
        labels:
          severity: warning
          service: ml-producer
        annotations:
          summary: "High ML task failure rate"
          description: "ML task failure rate is {{ $value | humanizePercentage }} over the last 5 minutes"

      - alert: MLProducerHighPublishLatency
        expr: |
          histogram_quantile(0.95, 
            rate(ml_producer_task_publish_duration_seconds_bucket[5m])
          ) > 0.5
        for: 5m
        labels:
          severity: warning
          service: ml-producer
        annotations:
          summary: "High ML task publish latency"
          description: "95th percentile publish latency is {{ $value }}s (threshold: 0.5s)"

      # Task-Specific Alerts
      - alert: TranscriptionTasksStalled
        expr: |
          rate(ml_producer_tasks_sent_total{task_type="transcribe_whisper"}[10m]) == 0
          and
          rate(ml_producer_tasks_sent_total{task_type="transcribe_whisper"}[1h]) > 0
        for: 10m
        labels:
          severity: warning
          service: ml-producer
          task_type: transcription
        annotations:
          summary: "No transcription tasks processed"
          description: "No transcription tasks have been sent in the last 10 minutes"

      - alert: LargeMessageSize
        expr: |
          histogram_quantile(0.95,
            rate(ml_producer_message_size_bytes_bucket[5m])
          ) > 100000
        for: 5m
        labels:
          severity: info
          service: ml-producer
        annotations:
          summary: "Large ML messages being sent"
          description: "95th percentile message size is {{ $value | humanize }}B (threshold: 100KB)"

      # Retry Alerts
      - alert: HighTaskRetryRate
        expr: |
          rate(ml_producer_task_retries_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
          service: ml-producer
        annotations:
          summary: "High ML task retry rate"
          description: "ML tasks are being retried at {{ $value | humanize }} per second"

  - name: ml_producer_slo_alerts
    interval: 1m
    rules:
      # SLO: 99.9% of tasks should be published successfully
      - alert: MLProducerSLOViolation
        expr: |
          (
            rate(ml_producer_tasks_sent_total{status="success"}[30m]) / 
            rate(ml_producer_tasks_sent_total[30m])
          ) < 0.999
        for: 5m
        labels:
          severity: warning
          service: ml-producer
          slo: "99.9% success rate"
        annotations:
          summary: "ML Producer SLO violation"
          description: "ML task success rate is {{ $value | humanizePercentage }} (SLO: 99.9%)"

      # SLO: 95% of tasks should be published within 100ms
      - alert: MLProducerLatencySLOViolation
        expr: |
          histogram_quantile(0.95,
            rate(ml_producer_task_publish_duration_seconds_bucket[30m])
          ) > 0.1
        for: 5m
        labels:
          severity: warning
          service: ml-producer
          slo: "95% < 100ms"
        annotations:
          summary: "ML Producer latency SLO violation"
          description: "95th percentile latency is {{ $value }}s (SLO: < 100ms)"