# KEDA Installation
# Apply with: kubectl apply --server-side -f https://github.com/kedacore/keda/releases/download/v2.13.0/keda-2.13.0.yaml
# Or use Helm:
# helm repo add kedacore https://kedacore.github.io/charts
# helm repo update
# helm install keda kedacore/keda --namespace keda --create-namespace --version 2.13.0

---
# KEDA Configuration for RabbitMQ
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: bookmarkai-ml
type: Opaque
stringData:
  connectionString: "amqp://bookmarkai:bookmarkai@rabbitmq.bookmarkai.svc.cluster.local:5672/bookmarkai"
---
# KEDA TriggerAuthentication for RabbitMQ
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: rabbitmq-trigger-auth
  namespace: bookmarkai-ml
spec:
  secretTargetRef:
    - parameter: host
      name: rabbitmq-secret
      key: connectionString