apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookmarkai-ml

resources:
  - namespace.yaml
  - keda-install.yaml
  - ml-workers-configmap.yaml
  - ml-workers-secrets.yaml
  - llm-worker-deployment.yaml
  - llm-worker-scaledobject.yaml
  - whisper-worker-deployment.yaml
  - whisper-worker-scaledobject.yaml
  - vector-worker-deployment.yaml
  - vector-worker-scaledobject.yaml
  - hpa-metrics-server.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: bookmarkai
  environment: base

images:
  - name: bookmarkai/llm-worker
    newTag: latest
  - name: bookmarkai/whisper-worker
    newTag: latest
  - name: bookmarkai/vector-worker
    newTag: latest