apiVersion: v1
kind: Secret
metadata:
  name: ml-workers-secrets
  namespace: bookmarkai-ml
type: Opaque
stringData:
  # Database
  DB_PASSWORD: "your-db-password"
  DATABASE_URL: "postgresql://bookmarkai:your-db-password@postgres.bookmarkai.svc.cluster.local:5432/bookmarkai"
  
  # API Keys
  ML_OPENAI_API_KEY: "your-openai-api-key"
  ANTHROPIC_API_KEY: "your-anthropic-api-key"
  PERPLEXITY_API_KEY: "your-perplexity-api-key"
  
  # AWS/S3
  AWS_ACCESS_KEY_ID: "your-aws-access-key"
  AWS_SECRET_ACCESS_KEY: "your-aws-secret-key"
  S3_BUCKET_NAME: "bookmarkai-ml-assets"
  
  # RabbitMQ
  MQ_USER: "bookmarkai"
  MQ_PASSWORD: "bookmarkai"
  MQ_VHOST: "bookmarkai"