/**
 * Error codes for the shares module
 */
export const ERROR_CODES = {
    DUPLICATE_SHARE: 'DUPLICATE_SHARE',
    INVALID_URL: 'INVALID_URL',
    UNSUPPORTED_PLATFORM: 'UNSUPPORTED_PLATFORM',
    SHARE_NOT_FOUND: 'SHARE_NOT_FOUND',
    SERVER_ERROR: 'SERVER_ERROR',
    UNAUTHORIZED: 'UNAUTHORIZED',
    IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  };