name: Database Seed Test

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'scripts/seed/**'
      - 'packages/api-gateway/src/db/schema/**'

jobs:
  test-seed:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: ankane/pgvector:latest
        env:
          POSTGRES_USER: bookmarkai
          POSTGRES_PASSWORD: bookmarkai_password
          POSTGRES_DB: bookmarkai
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run migrations
        run: npm run migrate
        env:
          NODE_ENV: ci
          DB_HOST: localhost
      
      - name: Run seed script
        run: npm run seed:ci
        env:
          NODE_ENV: ci
          DB_HOST: localhost
          CLEAN_SEED: 'true'
      
      - name: Verify seed data
        run: npm run seed:verify
        env:
          NODE_ENV: ci
          DB_HOST: localhost